export const pdfSections = [
  { id: 'torta_jalapeno', name: 'Torta de jalapeño en taza', startPage: 11, endPage: 12 },
  { id: 'torta_tocino_cheddar', name: 'Torta en taza de tocino y cheddar', startPage: 13, endPage: 14 },
  { id: 'aguacate_huevo', name: 'Aguacate relleno de huevo', startPage: 15, endPage: 16 },
  { id: 'aguacates_horno', name: 'Aguacates al horno con huevos y tocino', startPage: 17, endPage: 18 },
  { id: 'avena_canela', name: 'Avena falsa de canela', startPage: 19, endPage: 20 },
  { id: 'bollito_huevo_salchicha', name: 'Bollito de huevo y salchicha baja en carbohidratos', startPage: 21, endPage: 22 },
  { id: 'bollitos_huevo', name: 'Bollitos de huevo', startPage: 23, endPage: 24 },
  { id: 'cacerola_chorizo', name: 'Cacerola de chorizo para el desayuno', startPage: 25, endPage: 26 },
  { id: 'capas_desayuno', name: 'Capas de desayuno Keto', startPage: 27, endPage: 28 },
  { id: 'cereal_fresas', name: 'Crujiente keto cereal con fresas', startPage: 29, endPage: 30 },
  { id: 'cuadritos_huevo', name: 'Cuadritos de huevo para el desayuno', startPage: 31, endPage: 32 },
  { id: 'avena_canela_cetogenica', name: 'Deliciosa imitación de avena cetogénica con canela', startPage: 33, endPage: 34 },
  { id: 'desayuno_canela_nueces', name: 'Desayuno rápido de canela y nueces', startPage: 35, endPage: 36 },
  { id: 'frittata_pollo', name: 'Frittata de pollo keto', startPage: 37, endPage: 38 },
  { id: 'frittata_salchicha', name: 'Frittata de salchicha', startPage: 39, endPage: 40 },
  { id: 'frittata_sarten_hierro', name: 'Frittata en sartén de hierro', startPage: 41, endPage: 42 },
  { id: 'gacha_coco_mora', name: 'Gacha porridge de coco y mora azul', startPage: 43, endPage: 44 },
  { id: 'hot_cakes_calabaza', name: 'Hot cakes de calabaza y queso crema', startPage: 45, endPage: 46 },
  { id: 'hot_cakes_espagueti', name: 'Hot cakes de espagueti de calabacín', startPage: 47, endPage: 48 },
  { id: 'hot_cakes_proteina', name: 'Hot cakes de proteína y frambuesa', startPage: 49, endPage: 50 },
  { id: 'huevos_tocino_clasico', name: 'Huevos con tocino clásico', startPage: 51, endPage: 52 },
  { id: 'huevos_tazas_tocino', name: 'Riquísimos huevos en tazas de tocino', startPage: 53, endPage: 54 },
  { id: 'huevos_fritos', name: 'Huevos fritos', startPage: 55, endPage: 56 },
  { id: 'huevos_parmesanos', name: 'Huevos parmesanos', startPage: 57, endPage: 58 },
  { id: 'huevos_espinacas_cheddar', name: 'Huevos revueltos con espinacas y cheddar', startPage: 59, endPage: 60 },
  { id: 'huevos_queso_ricota', name: 'Huevos revueltos con queso ricota', startPage: 61, endPage: 62 },
  { id: 'huevos_queso_crema', name: 'Huevos revueltos con queso crema', startPage: 63, endPage: 64 },
  { id: 'huevos_tocino_sarten', name: 'Huevos y tocino al sartén', startPage: 65, endPage: 66 },
  { id: 'hot_cakes_tocino', name: 'Keto hot cakes de tocino', startPage: 67, endPage: 68 },
  { id: 'waffles_calabaza', name: 'Keto waffles con especias de calabaza', startPage: 69, endPage: 70 },
  { id: 'mcmuffin_keto', name: 'Mcmuffin estilo keto', startPage: 71, endPage: 72 },
  { id: 'muffins_matutinos', name: 'Muffins matutinos', startPage: 73, endPage: 74 },
  { id: 'nubes_huevo', name: 'Nubes de huevo', startPage: 75, endPage: 76 },
  { id: 'omelette_blanco_espinacas', name: 'Omelette blanco con espinacas', startPage: 77, endPage: 78 },
  { id: 'omelette_pollo_cali', name: 'Omelette Cali de pollo', startPage: 79, endPage: 80 },
  { id: 'omelette_cebollin_tocino', name: 'Omelette de cebollín y tocino', startPage: 81, endPage: 82 },
  { id: 'omelette_queso_cabra_espinacas', name: 'Omelette de queso de cabra y espinacas', startPage: 83, endPage: 84 },
  { id: 'omelette_queso_feta_pesto', name: 'Omelette de queso feta y pesto', startPage: 85, endPage: 86 },
  { id: 'omelette_salchicha_queso_feta', name: 'Omelette de salchicha y queso feta', startPage: 87, endPage: 88 },
  { id: 'omelette_jamon_queso_horno', name: 'Omelette de jamón y queso al horno', startPage: 89, endPage: 90 },
  { id: 'omelette_picoso_camaron', name: 'Omelette picoso de camarón', startPage: 91, endPage: 92 },
  { id: 'panqueques_calabaza', name: 'Panqueques de calabaza keto', startPage: 93, endPage: 94 },
  { id: 'panqueques_semillas_lino_almendras', name: 'Panqueques de semillas de lino y almendras', startPage: 95, endPage: 96 },
  { id: 'huevos_revueltos_perfectos', name: 'Perfectos huevos revueltos', startPage: 97, endPage: 98 },
  { id: 'queso_ricota_vainilla', name: 'Queso ricota con vainilla', startPage: 99, endPage: 100 },
  { id: 'quiche_cebolla_queso', name: 'Quiche de cebolla y queso', startPage: 101, endPage: 102 },
  { id: 'quiche_fajita_pollo', name: 'Quiche de fajita de pollo', startPage: 103, endPage: 104 },
  { id: 'quiche_keto', name: 'Quiche keto', startPage: 105, endPage: 106 },
  { id: 'huevos_salchicha_tocino', name: 'Riquísimos huevos cetogénicos envueltos en salchicha y tocino', startPage: 107, endPage: 108 },
  { id: 'huevos_revueltos_sabrosos', name: 'Sabrosos huevos revueltos', startPage: 109, endPage: 110 },
  { id: 'souffle_cebollin', name: 'Soufflé de cebollín keto', startPage: 111, endPage: 112 },
  { id: 'torta_pesto_tomate', name: 'Torta en taza de pesto de tomate keto', startPage: 113, endPage: 114 },
  { id: 'waffle_rollo_canela', name: 'Waffle disfrazado de rollo de canela', startPage: 115, endPage: 116 },
  { id: 'waffles_almendras_tocino', name: 'Waffles de almendras y tocino', startPage: 117, endPage: 118 },
  { id: 'huevos_rellenos_tocino', name: 'Huevos rellenos con tocino', startPage: 119, endPage: 120 },
  { id: 'waffles_brie_frambuesa', name: 'Waffles rellenos de brie y frambuesa', startPage: 121, endPage: 121 },
  { id: 'bebidas', name: 'Bebidas', startPage: 122, endPage: 122 },
  { id: 'batido_verde_proteina', name: 'Batido verde de proteína', startPage: 123, endPage: 124 },
  { id: 'cafe_cetogenico', name: 'Café cetogénico a prueba de balas', startPage: 125, endPage: 126 },
  { id: 'leche_almendras_mora', name: 'Leche de almendras y mora azul', startPage: 127, endPage: 128 },
  { id: 'leche_chocolate', name: 'Leche de chocolate de ensueño', startPage: 129, endPage: 130 },
  { id: 'leche_fresas_almendras', name: 'Leche de fresas y almendras', startPage: 131, endPage: 132 },
  { id: 'malteada_mora_proteina', name: 'Malteada de mora azul y proteína', startPage: 133, endPage: 134 },
  { id: 'matcha_latte_frio', name: 'Matcha latte frío', startPage: 135, endPage: 136 },
  { id: 'pastel_cafe_keto', name: 'Pastel de café keto', startPage: 137, endPage: 139 },
  { id: 'taza_coco_cafe', name: 'Taza con coco y café alto en fibra', startPage: 140, endPage: 141 },
  { id: 'te_mananero', name: 'Té mañanero desintoxicante', startPage: 142, endPage: 143 },
  { id: 'comidas_cenas', name: 'Comidas y Cenas', startPage: 144, endPage: 144 },
  { id: 'albondigas_pimienta', name: 'Albóndigas de pimienta', startPage: 145, endPage: 146 },
  { id: 'curry_coco', name: 'Curry de coco', startPage: 147, endPage: 148 },
  { id: 'asado_domingo', name: 'Delicioso asado de domingo', startPage: 149, endPage: 150 },
  { id: 'ensalada_pak_choi', name: 'Ensalada de pak choi con tofu', startPage: 151, endPage: 152 },
  { id: 'hamburguesa_invertida', name: 'Hamburguesa invertida keto', startPage: 153, endPage: 154 },
  { id: 'sandwich_pollo_tocino', name: 'Sándwich keto de pollo y tocino con aguacate', startPage: 155, endPage: 156 },
  { id: 'tiras_pollo', name: 'Tiras de pollo', startPage: 157, endPage: 158 },
  { id: 'albondigas_cheddar', name: 'Albóndigas cubiertas de cheddar', startPage: 159, endPage: 160 },
  { id: 'albondigas_pavo', name: 'Albóndigas de pavo keto', startPage: 161, endPage: 162 },
  { id: 'alitas_chipotle', name: 'Alitas de pollo al chipotle con mermelada de moras', startPage: 163, endPage: 164 },
  { id: 'arrachera_glaseado', name: 'Arrachera con glaseado y cebollas caramelizadas', startPage: 165, endPage: 166 },
  { id: 'arroz_coliflor', name: 'Arroz de coliflor con lima y cilantro', startPage: 167, endPage: 168 },
  { id: 'camaron_mani_curry', name: 'Camarón con maní al curry keto', startPage: 169, endPage: 170 },
  { id: 'camarones_mantequilla_ajo', name: 'Camarones a la mantequilla de ajo', startPage: 171, endPage: 172 },
  { id: 'camarones_tomate', name: 'Camarones al tomate', startPage: 173, endPage: 174 },
  { id: 'camarones_coco', name: 'Camarones con coco', startPage: 175, endPage: 176 },
  { id: 'camaron_picante_limon', name: 'Camarón picante a la parrilla con limón', startPage: 177, endPage: 178 },
  { id: 'camaron_sofrito', name: 'Camarón sofrito con sal y pimienta', startPage: 179, endPage: 180 },
  { id: 'champinones_rellenos', name: 'Champiñones rellenos de salchicha y queso crema', startPage: 181, endPage: 182 },
  { id: 'chile_poblano_horno', name: 'Chile poblano al horno', startPage: 183, endPage: 184 },
  { id: 'chili_beans_cetogenicos', name: 'Chili beans cetogénicos en olla de lento cocimiento sin frijoles', startPage: 185, endPage: 186 },
  { id: 'chuletas_cerdo_applewood', name: 'Chuletas de cerdo Applewood', startPage: 187, endPage: 188 },
  { id: 'chuletas_cerdo_asiaticas', name: 'Chuletas de cerdo asiáticas', startPage: 189, endPage: 190 },
  { id: 'cola_res_crock_pot', name: 'Cola de res en crock pot', startPage: 191, endPage: 192 },
  { id: 'col_rizada_estofada', name: 'Col rizada estofada', startPage: 193, endPage: 194 },
  { id: 'cordero_coccion_lenta', name: 'Cordero en olla de cocción lenta', startPage: 195, endPage: 196 },
  { id: 'costillas_asiaticas', name: 'Costillas keto estilo asiático', startPage: 197, endPage: 198 },
  { id: 'costillas_puerco', name: 'Costillas de puerco', startPage: 199, endPage: 200 },
  { id: 'costra_queso_cheddar', name: 'Costra de queso cheddar', startPage: 201, endPage: 202 },
  { id: 'tacos_desayuno', name: 'Tacos cetogénicos para el desayuno', startPage: 203, endPage: 204 },
  { id: 'tacos_desayuno_crujientes', name: 'Crujientes tacos cetogénicos para el desayuno', startPage: 205, endPage: 206 },
  { id: 'muslos_pollo_deliciosos', name: 'Deliciosos muslos de pollo para chuparse los dedos', startPage: 207, endPage: 208 },
  { id: 'ensalada_caprese', name: 'Ensalada caprese ligera', startPage: 209, endPage: 210 },
  { id: 'ensalada_col_rizada', name: 'Ensalada de col rizada', startPage: 211, endPage: 212 },
  { id: 'ensalada_pepino', name: 'Ensalada de pepino', startPage: 213, endPage: 214 },
  { id: 'ensalada_pepino_balsamico', name: 'Ensalada de pepino balsámico', startPage: 215, endPage: 216 },
  { id: 'ensalada_primavera', name: 'Ensalada primavera', startPage: 217, endPage: 218 },
  { id: 'ensalada_tomate_tocino', name: 'Ensalada de tomate y tocino', startPage: 219, endPage: 220 },
  { id: 'espaldilla_asada', name: 'Espaldilla asada a fuego lento', startPage: 221, endPage: 222 },
  { id: 'estofado_pollo', name: 'Estofado de pollo', startPage: 223, endPage: 224 },
  { id: 'ceviche_pescado', name: 'Fresco ceviche de pescado', startPage: 225, endPage: 226 },
  { id: 'guisado_cerdo_sureno', name: 'Guisado de cerdo sureño', startPage: 227, endPage: 229 },
  { id: 'hamburguesa_desayuno', name: 'Hamburguesa de desayuno con mantequilla de maní', startPage: 230, endPage: 231 },
  { id: 'hamburguesa_rellena_queso', name: 'Hamburguesa rellena de queso', startPage: 232, endPage: 233 },
  { id: 'hamburguesas_portobello', name: 'Hamburguesas de Portobello', startPage: 234, endPage: 235 },
  { id: 'hamburguesas_salmon', name: 'Hamburguesas de salmón', startPage: 236, endPage: 237 },
  { id: 'higado_pollo_ajo', name: 'Hígado de pollo al ajo', startPage: 238, endPage: 239 },
  { id: 'hot_dogs_rellenos_queso', name: 'Hot dogs estilo keto rellenos de queso', startPage: 240, endPage: 241 },
  { id: 'pizza_waffle', name: 'Keto pizza estilo waffle', startPage: 242, endPage: 243 },
  { id: 'alitas_picositas', name: 'Alitas picositas cetogénicas', startPage: 244, endPage: 245 },
  { id: 'lomo_cerdo_tocino', name: 'Lomo de cerdo envuelto en tocino', startPage: 246, endPage: 247 },
  { id: 'muslos_pollo_curry', name: 'Muslos de pollo al curry', startPage: 248, endPage: 249 },
  { id: 'pollo_pimenton', name: 'Pollo con pimentón', startPage: 250, endPage: 251 },
  { id: 'muslos_pollo_especias', name: 'Muslos de pollo con especias asiáticas', startPage: 252, endPage: 253 },
  { id: 'nasi_lemak', name: 'Nasi lemak ceto amigable', startPage: 254, endPage: 255 },
  { id: 'nuggets_pollo', name: 'Nuggets de pollo', startPage: 256, endPage: 257 },
  { id: 'pechuga_pavo_naranja', name: 'Pechuga de pavo a la naranja', startPage: 258, endPage: 259 },
  { id: 'pepinos_crema_agria', name: 'Pepinos con crema agria', startPage: 260, endPage: 261 },
  { id: 'lomo_cerdo_deshuesado', name: 'Perfecto lomo de cerdo deshuesado', startPage: 262, endPage: 263 },
  { id: 'picadillo_cajun', name: 'Picadillo Cajún', startPage: 264, endPage: 265 },
  { id: 'picadillo_tocino', name: 'Picadillo de tocino', startPage: 266, endPage: 267 },
  { id: 'enchiladas_cetogenicas', name: 'Enchiladas cetogénicas', startPage: 268, endPage: 269 },
  { id: 'piernas_pavo_chile', name: 'Piernas de pavo con chile', startPage: 270, endPage: 271 },
  { id: 'pimientos_rellenos_carne', name: 'Pimientos rellenos de carne', startPage: 272, endPage: 273 },
  { id: 'pizza_sarten_hierro', name: 'Pizza cetogénica en sartén de hierro', startPage: 274, endPage: 275 },
  { id: 'pizza_orillas_rellenas', name: 'Pizza cetogénica con orillas rellenas de queso', startPage: 276, endPage: 277 },
  { id: 'pizza_pollo_barbacoa', name: 'Pizza de pollo a la barbacoa', startPage: 278, endPage: 279 },
  { id: 'pizza_facil', name: 'Pizza Fácil', startPage: 280, endPage: 281 },
  { id: 'pizza_pimientos_albahaca', name: 'Pizza keto de pimientos y albahaca', startPage: 282, endPage: 283 },
  { id: 'pizzas_portobello', name: 'Pizzas de Portobello', startPage: 284, endPage: 285 },
  { id: 'pollo_tocino', name: 'Pollo envuelto en tocino', startPage: 286, endPage: 287 },
  { id: 'pollo_queso_coccion_lenta', name: 'Pollo con queso en olla de cocción lenta', startPage: 288, endPage: 289 },
  { id: 'pollo_satay', name: 'Pollo Satay', startPage: 290, endPage: 291 },
  { id: 'rib_eye_clasico', name: 'Rib eye clásico', startPage: 292, endPage: 293 },
  { id: 'rib_eye_rostizado', name: 'Rib eye rostizado', startPage: 294, endPage: 295 },
  { id: 'huevos_salchicha_tocino', name: 'Huevos envueltos en salchicha y tocino', startPage: 296, endPage: 297 },
  { id: 'rollitos_repollo', name: 'Rollitos de repollo con corned beef keto', startPage: 298, endPage: 299 },
  { id: 'rollo_carne', name: 'Rollo de carne cetogénico', startPage: 300, endPage: 301 },
  { id: 'albondigas_rellenas', name: 'Albóndigas rellenas en salsa de tomate natural', startPage: 302, endPage: 303 },
  { id: 'salchichas_verduras', name: 'Salchichas con verduras picositas', startPage: 304, endPage: 305 },
  { id: 'salchichas_rellenas', name: 'Salchichas rellenas de cebolla y queso', startPage: 306, endPage: 307 },
  { id: 'salmon_nueces', name: 'Salmón con nueces', startPage: 308, endPage: 309 },
  { id: 'salmon_jengibre', name: 'Salmón glaseado al jengibre', startPage: 310, endPage: 311 },
  { id: 'salmon_jarabe_maple', name: 'Salmón con jarabe de maple', startPage: 312, endPage: 313 },
  { id: 'salmon_eneldo', name: 'Salmón keto en salsa de eneldo', startPage: 314, endPage: 315 },
  { id: 'salmon_tomate_albahaca', name: 'Salmón con tomate y albahaca', startPage: 316, endPage: 317 },
  { id: 'vieiras_ajo_perejil', name: 'Salteado de vieiras con ajo y perejil', startPage: 318, endPage: 319 },
  { id: 'souffle_huevo_queso', name: 'Soufflé fácil de huevo y queso', startPage: 320, endPage: 321 },
  { id: 'tacos_cerdo', name: 'Tacos de cerdo', startPage: 322, endPage: 323 },
  { id: 'tacos_queso', name: 'Tacos de queso keto', startPage: 324, endPage: 325 },
  { id: 'pure_coliflor', name: 'Puré cetogénico de coliflor', startPage: 326, endPage: 327 },
  { id: 'tilapia_almendras', name: 'Tilapia con almendras', startPage: 328, endPage: 329 },
  { id: 'wraps_pollo_tocino', name: 'Wraps de pollo y tocino', startPage: 330, endPage: 331 },
  { id: 'dip', name: 'DIP', startPage: 332, endPage: 332 },
  { id: 'dip_chipotle', name: 'Dip cremoso de chipotle', startPage: 333, endPage: 334 },
  { id: 'gravy_almendras', name: 'Gravy de harina de almendras', startPage: 335, endPage: 336 },
  { id: 'mermelada_chia', name: 'Mermelada de chía amelocotonada', startPage: 337, endPage: 338 },
  { id: 'mermelada_chipotle', name: 'Mermelada de chipotle con moras', startPage: 339, endPage: 340 },
  { id: 'dip_salchichas', name: 'Salsa dip de salchichas', startPage: 341, endPage: 342 },
  { id: 'dip_tocino', name: 'Salsa dip de tocino', startPage: 343, endPage: 344 },
  { id: 'refrigerios', name: 'Refrigerios', startPage: 345, endPage: 345 },
  { id: 'muffins_pan_frances', name: 'Muffins de pan francés estilo keto', startPage: 346, endPage: 347 },
  { id: 'pan_proteina', name: 'Pan de proteína', startPage: 348, endPage: 349 },
  { id: 'barras_cacahuate', name: 'Barras de crema de cacahuate para el desayuno', startPage: 350, endPage: 351 },
  { id: 'berenjenas_parmesano', name: 'Berenjenas con parmesano', startPage: 352, endPage: 353 },
  { id: 'biscuits_coco', name: 'Biscuits de coco bajos en carbohidratos', startPage: 354, endPage: 355 },
  { id: 'donas_calabaza', name: 'Bolitas de donas de calabaza keto con cardamomo', startPage: 356, endPage: 357 },
  { id: 'bollitos_dos_quesos', name: 'Bollitos de dos quesos', startPage: 358, endPage: 359 },
  { id: 'bollitos_mora_azul', name: 'Bollitos de mora azul bajos en carbohidratos', startPage: 360, endPage: 361 },
  { id: 'bollitos_mora_crema', name: 'Bollitos de mora azul y crema ácida', startPage: 362, endPage: 363 },
  { id: 'bollitos_mora_limon', name: 'Bollitos de mora azul y limón', startPage: 364, endPage: 365 },
  { id: 'bollos_almendra_psyllium', name: 'Esponjosos bollos de almendra y Psyllium plantago', startPage: 366, endPage: 367 },
  { id: 'crepas_canela', name: 'Crepas de canela', startPage: 368, endPage: 369 },
  { id: 'brownies_nueces', name: 'Brownies cetogénicos con nueces', startPage: 370, endPage: 371 },
  { id: 'donas_keto', name: 'Donas keto', startPage: 372, endPage: 373 },
  { id: 'esparragos_pecorino', name: 'Espárragos y queso pecorino', startPage: 374, endPage: 375 },
  { id: 'cupcakes_canela', name: 'Esponjocitos cupcakes de canela, nuez y harina de coco', startPage: 376, endPage: 377 },
  { id: 'galletas_lavanda', name: 'Galletas de lavanda', startPage: 378, endPage: 379 },
  { id: 'jalapenos_nueces', name: 'Jalapeños al escabeche rellenos de nueces', startPage: 380, endPage: 381 },
  { id: 'jalapenos_poppers', name: 'Jalapeños poppers', startPage: 382, endPage: 383 },
  { id: 'pan_calabaza', name: 'Keto pan de calabaza', startPage: 384, endPage: 385 },
  { id: 'pan_frances', name: 'Keto pan francés', startPage: 386, endPage: 387 },
  { id: 'pan_cetogenico', name: 'Pan cetogénico', startPage: 388, endPage: 390 },
  { id: 'pastel_chocolate', name: 'Pastel cetogénico de chocolate obscuro y nueces', startPage: 391, endPage: 392 },
  { id: 'pan_nube', name: 'Pan nube con solo 4 ingredientes', startPage: 393, endPage: 394 },
  { id: 'nachos_coliflor', name: 'Nachos cetogénicos de coliflor', startPage: 395, endPage: 396 },
  { id: 'nueces_romero', name: 'Nueces asadas con mantequilla y romero', startPage: 397, endPage: 398 },
  { id: 'palomitas_coliflor', name: 'Palomitas de coliflor', startPage: 399, endPage: 400 },
  { id: 'pan_focaccia', name: 'Pan focaccia de linaza', startPage: 401, endPage: 402 },
  { id: 'tostadita_cetogenica', name: 'Tostadita cetogénica', startPage: 403, endPage: 404 },
  { id: 'yogur_coco', name: 'Yogur cremoso de coco', startPage: 405, endPage: 406 },
  { id: 'sopas_caldos', name: 'Sopas y Caldos', startPage: 407, endPage: 407 },
  { id: 'sopa_tomate', name: 'Rica sopa de tomate', startPage: 408, endPage: 409 },
  { id: 'sopa_cebolla', name: 'Sopa de cebolla francesa clásica', startPage: 410, endPage: 411 },
  { id: 'sopa_calabaza', name: 'Sopa de calabaza', startPage: 412, endPage: 413 },
  { id: 'sopa_cheddar_tocino', name: 'Sopa de cheddar y tocino', startPage: 414, endPage: 415 },
  { id: 'sopa_enchilada', name: 'Sopa enchilada', startPage: 416, endPage: 417 },
  { id: 'sopa_jalapenos', name: 'Sopa de jalapeños', startPage: 418, endPage: 419 },
  { id: 'sopa_pollo_huevo', name: 'Sopa de pollo y huevo', startPage: 420, endPage: 421 },
  { id: 'sopa_salchicha_pimienta', name: 'Sopa de salchicha y pimienta keto', startPage: 422, endPage: 423 },
  { id: 'sopa_guisantes_menta', name: 'Sopa de guisantes con menta', startPage: 424, endPage: 425 },
  { id: 'sopa_zanahoria', name: 'Sopa de zanahoria', startPage: 426, endPage: 427 },
];

export const getTotalPages = () => {

    return Math.max(...pdfSections.map(section => section.endPage));

};

export const getSectionById = (id) => {

    return pdfSections.find(section => section.id===id);

}